### ISSUE TITLE
Compilation of translator is failing on clean machine

### ISSUE THREAD

**Issue by eabatalov** [olonho/carkot#1]
carkot/car_fmw$ make
cd /home/eugene/teach/projects/kotlin_native/carkot/car_fmw/../translator && ./gradlew jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.0.2/kotlin-gradle-plugin-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-project/1.0.2/kotlin-project-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.0.2/kotlin-stdlib-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-android-extensions/1.0.2/kotlin-android-extensions-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-core/1.0.2/kotlin-gradle-plugin-core-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.0.2/kotlin-gradle-plugin-api-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-runtime/1.0.2/kotlin-runtime-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.2/kotlin-compiler-embeddable-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-annotation-processing/1.0.2/kotlin-annotation-processing-1.0.2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.0.2/kotlin-gradle-plugin-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.0.2/kotlin-stdlib-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-android-extensions/1.0.2/kotlin-android-extensions-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-core/1.0.2/kotlin-gradle-plugin-core-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.0.2/kotlin-gradle-plugin-api-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-runtime/1.0.2/kotlin-runtime-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.2/kotlin-compiler-embeddable-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-annotation-processing/1.0.2/kotlin-annotation-processing-1.0.2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.0.1/kotlin-stdlib-1.0.1.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-project/1.0.1/kotlin-project-1.0.1.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler/1.0.3/kotlin-compiler-1.0.3.pom
Download https://jitpack.io/com/github/jshmrsn/karg/a636b3e/karg-a636b3e.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-runtime/1.0.1/kotlin-runtime-1.0.1.pom
Download https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.0.1/kotlin-stdlib-1.0.1.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler/1.0.3/kotlin-compiler-1.0.3.jar
Download https://jitpack.io/com/github/jshmrsn/karg/a636b3e/karg-a636b3e.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-runtime/1.0.1/kotlin-runtime-1.0.1.jar
Download https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
:compileKotlin
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (68, 23): Type inference failed: inline fun <K, V> Map<K, V>.forEach(action: (Map.Entry<K, V>) -> kotlin.Unit): kotlin.Unit
cannot be applied to
receiver: HashMap<String, ClassCodegen>  arguments: ((Map.Entry<String, ClassCodegen>, ???) -> kotlin.Unit)

e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (68, 31): Type mismatch: inferred type is (Map.Entry<String, ClassCodegen>, ???) -> kotlin.Unit but (Map.Entry<String, ClassCodegen>) -> kotlin.Unit was expected
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (68, 33): Expected one parameter of type Map.Entry<String, ClassCodegen>
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (68, 36): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (85, 23): Type inference failed: inline fun <K, V> Map<K, V>.forEach(action: (Map.Entry<K, V>) -> kotlin.Unit): kotlin.Unit
cannot be applied to
receiver: HashMap<String, ClassCodegen>  arguments: ((Map.Entry<String, ClassCodegen>, ???) -> kotlin.Unit)

e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (85, 31): Type mismatch: inferred type is (Map.Entry<String, ClassCodegen>, ???) -> kotlin.Unit but (Map.Entry<String, ClassCodegen>) -> kotlin.Unit was expected
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (85, 33): Expected one parameter of type Map.Entry<String, ClassCodegen>
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/ClassCodegen.kt: (85, 36): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/FunctionCodegen.kt: (48, 73): Unresolved reference: getOrDefault
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/FunctionCodegen.kt: (48, 113): Type inference failed: Not enough information to infer parameter K in constructor HashMap<K : Any!, V : Any!>()
Please specify it explicitly.

e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (22, 36): Type inference failed: inline fun <K, V> Map<K, V>.forEach(action: (Map.Entry<K, V>) -> kotlin.Unit): kotlin.Unit
cannot be applied to
receiver: HashMap<String, Stack<Pair<LLVMVariable, Int>>>  arguments: ((Map.Entry<String, Stack<Pair<LLVMVariable, Int>>>, ???) -> kotlin.Unit)

e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (22, 44): Type mismatch: inferred type is (Map.Entry<String, Stack<Pair<LLVMVariable, Int>>>, ???) -> kotlin.Unit but (Map.Entry<String, Stack<Pair<LLVMVariable, Int>>>) -> kotlin.Unit was expected
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (22, 46): Expected one parameter of type Map.Entry<String, Stack<Pair<LLVMVariable, Int>>>
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (22, 49): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (26, 48): Unresolved reference: getOrDefault
e: /home/eugene/teach/projects/kotlin_native/carkot/translator/src/main/kotlin/org/kotlinnative/translator/VariableManager.kt: (36, 42): Unresolved reference: getOrDefault
:compileKotlin FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileKotlin'.
  
  > Compilation error. See log for more details
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                         option to get more log output.

BUILD FAILED

Total time: 46.298 secs
make: **\* [/home/eugene/teach/projects/kotlin_native/carkot/car_fmw/../translator/build/libs/translator-1.0.jar] Error 1

**Comment by e5l** [comment]
jdk version?

**Comment by eabatalov** [comment]
Is JDK version somehow influences Kotlin compiler errors?
javac -version shows:
javac 1.7.0_95

**Comment by e5l** [comment]
Yep, I think generic errors disappear after update to 1.8.

**Comment by eabatalov** [comment]
Ok
